all:
	g++ -O2 -std=c++11 empty_run.cpp -o empty_run
	g++ -O2 -std=c++11 naive.cpp -o naive
	g++ -O2 -std=c++11 numbers.cpp -o numbers
	g++ -O2 -std=c++11 numbers_5_heuristic.cpp -o numbers_5_heuristic
	g++ -O2 -std=c++11 numbers_oddity_heuristic.cpp -o numbers_oddity_heuristic
	g++ -O2 -std=c++11 numbers_permutation_shifts.cpp -o numbers_permutation_shifts
	g++ -O2 -std=c++11 words.cpp -o words
	g++ -O2 -std=c++11 words_in_set.cpp -o words_in_set
	g++ -O2 -std=c++11 words_in_unordered_set.cpp -o words_in_unordered_set
	g++ -O2 -std=c++11 words_oddity_heuristic.cpp -o words_oddity_heuristic
	g++ -O2 -std=c++11 64bits.cpp -o 64bits
	g++ -O2 -std=c++11 64bits_in_set.cpp -o 64bits_in_set
	g++ -O2 -std=c++11 64bits_in_unordered_set.cpp -o 64bits_in_unordered_set
	./empty_run
	./naive
	./numbers
	./numbers_5_heuristic
	./numbers_oddity_heuristic
	./numbers_permutation_shifts
	./words
	./words_in_set
	./words_in_unordered_set
	./words_oddity_heuristic
	./64bits
	./64bits_in_set
	./64bits_in_unordered_set
	rm ./empty_run	
	rm ./naive
	rm ./numbers
	rm ./numbers_5_heuristic
	rm ./numbers_oddity_heuristic
	rm ./numbers_permutation_shifts
	rm ./words
	rm ./words_in_set
	rm ./words_in_unordered_set
	rm ./words_oddity_heuristic
	rm ./64bits
	rm ./64bits_in_set
	rm ./64bits_in_unordered_set

