all:
	g++ -O2 -std=c++11 empty_run.cpp -o empty_run
	g++ -O2 -std=c++11 numbers.cpp -o numbers
	g++ -O2 -std=c++11 numbers_const.cpp -o numbers_const
	g++ -O2 -std=c++11 numbers_permutation_shifts.cpp -o numbers_permutation_shifts	
	g++ -O2 -std=c++11 64bits.cpp -o 64bits	
	g++ -O2 -std=c++11 64bits_local.cpp -o 64bits_local
	g++ -O2 -std=c++11 64bits_smart_index.cpp -o 64bits_smart_index
	g++ -O2 -std=c++11 64bits_binary_search.cpp -o 64bits_binary_search
	g++ -O2 -std=c++11 words_smart_memcmp.cpp -o words_smart_memcmp
	g++ -O2 -std=c++11 words_smart_index_and_memcmp.cpp -o words_smart_index_and_memcmp
	./empty_run
	./numbers
	./numbers_const
	./numbers_permutation_shifts
	./64bits
	./64bits_local
	./64bits_smart_index
	./64bits_binary_search
	./words_smart_memcmp
	./words_smart_index_and_memcmp
	rm ./empty_run	
	rm ./numbers
	rm ./numbers_const
	rm ./numbers_permutation_shifts
	rm ./64bits
	rm ./64bits_local
	rm ./64bits_smart_index
	rm ./64bits_binary_search
	rm ./words_smart_memcmp
	rm ./words_smart_index_and_memcmp
