// this is just a stub, real code should be generated by python

void solve_5(double* a, double* b, double* x)
{
    x[0] = b[0];
    x[1] = b[1];
    x[2] = b[2];
    x[3] = b[3];
    x[4] = b[4];
}

