all:
	g++ experiments.cpp -std=c++14 -O3 -o experiments
	g++ measurement.cpp -std=c++14 -O3 -o measurement
debug:
	g++ experiments.cpp -std=c++14 -O0 -g -o experiments
measurements:
	./measurement
clean:
	rm experiments
	rm measurement

