all:
	g++ -O2 -std=c++11 numbers_5_heuristic.cpp -o numbers_5_heuristic
	g++ -O2 -std=c++11 numbers_oddity_heuristic.cpp -o numbers_oddity_heuristic
	g++ -O2 -std=c++11 numbers_permutation_shifts.cpp -o numbers_permutation_shifts
	g++ -O2 -std=c++11 words_oddity_heuristic.cpp -o words_oddity_heuristic
	./numbers_5_heuristic
	./numbers_oddity_heuristic
	./numbers_permutation_shifts
	./words_oddity_heuristic
clean:
	rm ./numbers_5_heuristic
	rm ./numbers_oddity_heuristic
	rm ./numbers_permutation_shifts
	rm ./words_oddity_heuristic

