[package]
name = "rational_bounds"
version = "0.1.0"
authors = ["Oleksandr Kaleniuk <ok@wordsandbuttons.online>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
