all:
	clang++ -O2 -std=c++14 -march=native andand.cpp -o andand
	./andand
	rm ./andand
	clang++ -O2 -std=c++14 -march=native and.cpp -o and
	./and
	rm ./and
	clang++ -O2 -std=c++14 -march=native mul.cpp -o mul
	./mul
	rm ./mul
	clang++ -O2 -std=c++14 -march=native minus_mul_plus.cpp -o minus_mul_plus
	./minus_mul_plus
	rm ./minus_mul_plus
	clang++ -O2 -std=c++14 -march=native andand_double.cpp -o andand_double
	./andand_double
	rm ./andand_double
	clang++ -O2 -std=c++14 -march=native minus_mul_plus_double.cpp -o minus_mul_double_plus
	./minus_mul_double_plus
	rm ./minus_mul_double_plus
	clang++ -O2 -std=c++14 -march=native compare_zero.cpp -o compare_zero
	./compare_zero
	rm ./compare_zero
