all:
	clang++ -O2 -std=c++14 -march=native andand.cpp -o andand
	./andand
	rm ./andand
	clang++ -O2 -std=c++14 -march=native and.cpp -o and
	./and
	rm ./and
	clang++ -O2 -std=c++14 -march=native mul.cpp -o mul
	./mul
	rm ./mul
	clang++ -O2 -std=c++14 -march=native minus_mul.cpp -o minus_mul
	./minus_mul
	rm ./minus_mul
